version: 2.1

workflows:
  build:
    jobs:
      - test-job

jobs:
  test-job:
    docker:
      - image: cimg/node:20.19.0-browsers  # Use image with browsers for Cypress
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Run tests with intelligent runner
          command: npm run test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
