name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: "26.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: pnpm install 🔧 # Install
        run: |
          pnpm install --frozen-lockfile
      - name: pnpm run build 🔧 # Build
        run: |
          pnpm run build
      - name: pnpm run test 🔧 # Test
        run: |
          pnpm run test

      - name: Deploy 🚀 # Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.

